# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  docker: benefex/docker@volatile
  gcp-cli: circleci/gcp-cli@3.0.1
  gcp-gcr: circleci/gcp-gcr@0.15.1

defaults:
  default_executor: &default_executor
    docker:
      - image: cimg/openjdk:11.0-browsers
        auth:
          username: $DOCKERHUB_BOT_USERNAME
          password: $DOCKERHUB_BOT_PASSWORD
    environment:
      _JAVA_OPTIONS: -Xmx512m -Djdk.tls.client.protocols="TLSv1,TLSv1.1,TLSv1.2"
    working_directory: ~/project
    resource_class: small

jobs:
  build-and-push-image:
    <<: *default_executor
    parallelism: 1
    resource_class: medium
    steps:  
      - checkout
      - run:
          name: Install GCloud
          command: |
            echo "deb http://packages.cloud.google.com/apt cloud-sdk-stretch main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk kubectl      
      - run: 
          name: Store ClamAV service account 
          command: echo $GCLOUD_CLAMAV_SERVICE_ACCOUNT_KEY > /tmp/gcloud-clamav-service-account.json
      - run:
          name: Authenticate with GCloud
          command: |
            gcloud auth activate-service-account --key-file=/tmp/gcloud-clamav-service-account.json
            gcloud -q config set project $GCLOUD_DEV_PROJECT
            gcloud auth configure-docker europe-west1-docker.pkg.dev
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            ls
            cd ./cloudrun-malware-scanner/
            docker build -t malware-scanner:latest .
      - deploy:
          name: Push Docker image
          command: |
            docker image tag malware-scanner:latest \europe-west1-docker.pkg.dev/benefex-onehub-dev/cloud-run-source-deploy/malware-scanner:latest
            docker push europe-west1-docker.pkg.dev/benefex-onehub-dev/cloud-run-source-deploy/malware-scanner:latest
workflows:
  commit:
    jobs:
      - build-and-push-image:
          context: gcloud
