# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  docker: benefex/docker@volatile
  gcp-cli: circleci/gcp-cli@3.0.1

jobs:
  push_image:
    executor: gcp-cli/default
    steps:
      - run:
          name: Install GCloud
          command: |
            echo "deb http://packages.cloud.google.com/apt cloud-sdk-stretch main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk
      - run:
          name: Store gcloud service account
          command: echo $GCLOUD_API_TESTS_SERVICE_ACCOUNT > /tmp/gcloud-service-account.json
      - run:
          name: Authenticate with GCloud
          command: |
            gcloud auth activate-service-account --key-file=/tmp/gcloud-service-account.json
            gcloud -q config set project $GCLOUD_GKE_DEV_PROJECT_NAME
  build:
    working_directory: /malware-scanner
    docker:
      - image: europe-west1-docker.pkg.dev/benefex-onehub-dev/cloud-run-source-deploy/malware-scanner
        auth:
          username: $GCLOUD_CLAMAV_SERVICE_ACCOUNT
          password: $GCLOUD_CLAMAV_SERVICE_ACCOUNT_KEY
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run: echo "Building new malware scanner image"
      - run: 
          name: Build Docker image 
          command: |
            docker build -t clamav .
      - run: 
          name: Push Docker image to Google Artifact Repository 
          command: |
            docker tag europe-west1-docker.pkg.dev/benefex-onehub-dev/cloud-run-source-deploy/malware-scanner:latest
            docker push europe-west1-docker.pkg.dev/benefex-onehub-dev/cloud-run-source-deploy/malware-scanner:latest
