# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run: echo "this is the build job - configure auth/image tomorrow :)"
  test:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run: echo "this is the test job"
