# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  docker: benefex/docker@volatile
  gcp-cli: circleci/gcp-cli@3.0.1
  gcp-gcr: circleci/gcp-gcr@0.15.1

jobs:
  build-and-push-image:
    docker: 
       - image: circleci/python:3.8
    steps:  
      - checkout
      - run:
          name: Install GCloud
          command: gcloud components install
      - run:
          name: Store gcloud service account
          command: echo $GCLOUD_CLAMAV_SERVICE_ACCOUNT_KEY > /tmp/gcloud-clamav-service-account.json
      - run:
          name: Authenticate with GCloud
          command: |
            gcloud auth activate-service-account --key-file=/tmp/gcloud-clamav-service-account.json
            gcloud -q config set project $GCLOUD_GKE_DEV_PROJECT_NAME
            echo "Authenticated"
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t europe-west1-docker.pkg.dev/benefex-onehub-dev/cloud-run-source-deploy/malware-scanner:v1 .
      - deploy:
          name: Push Docker image
          command: |
            docker login gcr.io
            docker push europe-west1-docker.pkg.dev/benefex-onehub-dev/cloud-run-source-deploy/malware-scanner:v1

workflows:
  commit:
    jobs:
      - build-and-push-image:
          context: gcloud
